name: 'Get TF version.'
description: 'Get the version of TF that is installed'
inputs:
outputs:
  stdout: 
    description: "Output number"
    value: ${{ steps.terraform-version.outputs.stdout }}
runs:
  using: "composite"
  steps: 
    - id: terraform-version
      run: |
        stdout="$(terraform --version)"
        echo "::set-output name=stdout::${stdout}"
      shell: bash
