name: 'Terraform Plan'
description: 'Preview your terraform plan'
inputs: {}
outputs:
  has_output:
    description: "has output"
    value: ${{ steps.plan.outputs.has_output }}
  output:
    description: "output"
    value: ${{ steps.plan.outputs.output }}
runs:
  using: "composite"
  steps: 
    - name: Terraform Plan
      shell: bash
      id: plan
      working-directory: terraform/${{ matrix.dir }}
      run: ${{ github.action_path }}/plan.sh
