name: 'Terraform Plan'
description: 'Preview your terraform plan'
inputs: {}
outputs:
  stdout:
    description: "terraform plan stdout"
    value: ${{ steps.plan.outputs.stdout }}
  exitcode:
    description: "terraform plan exitcode"
    value: ${{ steps.plan.outputs.exitcode }}
runs:
  using: "composite"
  steps: 
    - name: Terraform Plan
      shell: bash
      id: plan
      working-directory: terraform/${{ matrix.dir }}
      # Follows tips from:
      # https://github.community/t/set-output-truncates-multiline-strings/16852/5
      run: |
        # Disables the immediate action failure due to exit code 2 on changes detected
        set +e
        plan_stdout="$(terraform plan -no-color -detailed-exitcode)"
        plan_exitcode="$?"
        plan_stdout="${plan_stdout//'%'/'%25'}"
        plan_stdout="${plan_stdout//$'\n'/'%0A'}"
        plan_stdout="${plan_stdout//$'\r'/'%0D'}"

        echo "::set-output name=stdout::${plan_stdout}"
        echo "::set-output name=exitcode::${plan_exitcode}"
