name: 'Get TF version.'
description: 'Get the version of TF that is installed'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  stdout:
    description: "Output number"
    value: ${{ steps.terraform-version.outputs.stdout }}
  help:
    description: "Output number"
    value: ${{ steps.terraform-help.outputs.stdout }}
runs:
  using: "composite"
  steps: 
    - id: terraform-version
      run: |
        stdout="$(terraform --version)"
        echo "::set-output name=stdout::${stdout}"
      shell: bash
    - id: terraform-help
      run: |
        stdout="$(terraform --help)"
        echo "::set-output name=stdout::${stdout}"
      shell: bash
    - id: terraform-recursive
      uses: abatilo/terraform-composite-action@master
