on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
    - id: tf
      uses: abatilo/terraform-composite-action@master
    - run: echo random-number ${{ steps.tf.outputs.stdout }} 
      shell: bash
